### ISSUE TITLE
Component name

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim-Psr7#1]
We can't use `Slim\Http` as we need that for Slim itself.

Options: 

1. `Slim\Psr7`
2. `Slim\HttpMessage`

**Comment by codeguy** [comment]
I vote `Slim\Psr7`.

**Comment by tuupola** [comment]
I don't have any strong feelings about this. But since the repository is already named `Slim-Psr7` class name should also be `Slim\Psr7` or OCD kicks in.

**Comment by akrabat** [comment]
The repo is brand new & can be changed.. It's a given that we'd match namespace name :)

**Comment by mathmarques** [comment]
`Slim\Psr7` +1

**Comment by xcorp1986** [comment]
Slim\Psr7 +1
