### ISSUE TITLE
Ensure headers are consistent

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim-Psr7#11]
* Ensure that our headers implementation is completely compliant with PSR-7
* Ensure that `getHeader()` and `getHeaders()` are consistent. See https://github.com/slimphp/Slim/issues/2400

Migrated from https://github.com/slimphp/Slim-Http/issues/61

**Comment by schmengler** [comment]
Glad that the issue is being addressed. This caused me some headache when passing a modified Slim request object from the environment to a Guzzle client and the headers with HTTP_ prefix got lost.

**Comment by sridesmet** [comment]
> Glad that the issue is being addressed. This caused me some headache when passing a modified Slim request object from the environment to a Guzzle client and the headers with HTTP_ prefix got lost.
> 
> A workaround is to reset the original keys, using reflection:
> 
> ```
>     private function resetHeaderOriginalKeys(Request $request): void
>     {
>         $headersProperty = new \ReflectionProperty(Request::class, 'headers');
>         $headersProperty->setAccessible(true);
>         /** @var Headers $headers */
>         $headers = $headersProperty->getValue($request);
>         foreach ($headers as $key => $header) {
>             $headers->set($key, $header['value']);
>         }
>         $headersProperty->setAccessible(false);
>     }
> ```

Here is your code in a middleware: https://gist.github.com/sridesmet/a3e0a6f3a3515aaf5d5b4b42479e8c67
