### ISSUE TITLE
Validation is processed twice

### ISSUE THREAD

**Issue by mapogolions** [slimphp/Slim-Psr7#117]
```php
$msg = new Message();
$msg->withHeader("name", "value");
[calls]
Message::withHeader($name, $string) [Message.php]
  Headers::validateHeaderName($name);
  Headers::validateHeaderValue($value);
  ...
  $clone->headers->setHeader($name, $value)
    Headers::setHeader($name, $value) [Headers.php]
       $values = $this->validateAndTrimHeader($name, $values);
       ...
       Headers::validateHeaderName($name);
       Headers::validateHeaderValue($value);
       ...
```
The same is true for the `withAddedHeader` method. I don't know how to redesign the code to create pull request.

**Comment by adriansuter** [comment]
We could for example add a new method to `Headers` called `setValidatedHeader($name, $value)` that gets called if and only if the variables were validated already.

But to me, I'd rather validate twice, than adding a method that could lead to miss-usages.

**Comment by mapogolions** [comment]
"Entities should not be multiplied without necessity" - i like it. The operation is not so expensive. But I liked Slim3.x style and current solution  seems little bit unnatural.
