### ISSUE TITLE
Reuse base class code

### ISSUE THREAD

**Issue by mapogolions** [slimphp/Slim-Psr7#121]
The abstract class `Message`, among others, defines two protected properties - `$headers` & `$body`. Any derived class will be inherit them. In paticular,  two classes `Request` & `Response`.  But classes define constructor parameters differently. 
- `Request::__construct(..., HeadersInterface $headers, StreamInterface $body)`
- `Response::__construct(..., ?HeadersInterface $headers, ?StreamInterface $body)`
If the base class (`Message`) defines the constructor, what would be the default behavior ?
`?HeadersInterface or HeadersInterface` & `?StreamInterface or StreamInterface`.

**Comment by l0gicgate** [comment]
I think we should make it optional for both `::__construct(..., ?HeadersInterface $headers, ?StreamInterface $body)`
