### ISSUE TITLE
Remove PHP 7.4 allowed failure when Prophecy PR merged

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim-Psr7#126]
We need to remove `7.4` from the `allow_failures` array in the Travis config when https://github.com/phpspec/prophecy/pull/432 is merged

**Comment by l0gicgate** [comment]
The PR has been merged. This is an easy pick. Who wants it 😂

**Comment by theodorejb** [comment]
A new release of phpspec/prophecy has to be published first.
