### ISSUE TITLE
Response headers include received Authorization header

### ISSUE THREAD

**Issue by geirp** [slimphp/Slim-Psr7#130]
The Response constructor will by default create a Headers object to collect headers to be sent. The Headers  constructor will call setHeaders() which will call parseAuthorizationHeader(). parseAuthorizationHeader() will try to create an Authorization header from data found in $_SERVER.

The result of this is that the Response headers include a copy of the Authorization header received in the request being processed.

The code comment for parseAuthorizationHeader() reads: "Parse incoming headers and determine Authorization header from original headers". My interpretation is that this code was never intended to be used for a Response.

**Comment by l0gicgate** [comment]
We need to fix this @adriansuter . This is definitely a bug. We may have to create `RequestHeaders` and `ResponseHeaders` which will could extend an abstract `Headers` object instead so we can differentiate their origins. While they are similar, `parseAuthorizationHeader` should not be called when we instantiate response headers.

**Comment by adriansuter** [comment]
Isn't it possible to simply provide the globals here, or do we need them elsewhere?
https://github.com/slimphp/Slim-Psr7/blob/1f8bb509f88b93c984ae68d7fef5769c56cad9f6/src/Response.php#L127

That is
```php
        $this->headers = $headers ? $headers : new Headers([], []);
```

I quickly made a test and run phpunit.
```php
    // \Slim\Tests\Psr7\ResponseTest
    public function testResponseHeadersDoNotContainAuthorizationHeader()
    {
        $_SERVER = Environment::mock(
            [
                'PHP_AUTH_USER' => 'foo'
            ]
        );

        $response = new Response();
        $this->assertEmpty($response->getHeaders());
    }
```

The test fails without the modification mentioned above. But with the change, all tests succeed. Could that be a BC?

**Comment by adriansuter** [comment]
@l0gicgate what do you think?

**Comment by l0gicgate** [comment]
@adriansuter that would also work yes. Probably the simplest fix.
