### ISSUE TITLE
Response::withSomething returns instance of Message instead of Response

### ISSUE THREAD

**Issue by noahboegli** [slimphp/Slim-Psr7#146]
When calling a "with" method on a Response (and also Request) object, the returned type is not Response (or Request) but rather Message. 

```php
    public function home(Request $request, Response $response, array $args){   
        //Type of $response is Response (Slim\Psr7\Response)
        $response= $response->withHeader("test", "value");
        //Type of $response is now Message (Slim\Psr7\Message)  
        ....     
    }
```

This is not an issue until you need to use Response (or Request) methods that are not common to the Message object.

Cheers,
Noah

**Comment by l0gicgate** [comment]
I think this may have to do with the fact that we use `@inheritdoc` which makes the `withX` which reference the `MessageInterface`. The solution would be to add return tags on those methods and specify that it returns `ResponseInterface` instead

**Comment by noahboegli** [comment]
Correct, after further testing, I have the following:
```php
    public function home(Request $request, Response $response, array $args){   
        $response= $response->withHeader("test", "value");
        $isResponse = $response instanceOf Response;
        var_dump($isResponse); // True
    }
```
Which confirms that it is only a PHPDoc issue.
Thanks!
