### ISSUE TITLE
Cookie default-fallback is not working if value is `null`

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim-Psr7#149]
Not sure it that is an issue, but the following test fails.

```php
        $cookies = new Cookies(['expires' => null]);

        $this->assertFalse($cookies->get('not-set', false));
        $this->assertNull($cookies->get('expires', 'Wed, 26 Jan 2020 12:00:00 GMT'));
```

We pass `expires` to be `null` in the constructor. The method `$cookies->get()` would check if there is a value defined for the given name and if not, it returns the second given parameter (default-fallback). The first assert-line is working as expected, but the second one would not return `null`, which it should in my opinion.

This is because the method `$cookies->get()` uses `isset` to check the existence of an array key. This function returns `false` if the key does not exist or if the value is `null`. See https://github.com/slimphp/Slim-Psr7/blob/e4be5e068e0ebea973d7306f40356fc47a1e600f/src/Cookies.php#L90-L93

Should we change that to `array_key_exists`?

**Comment by l0gicgate** [comment]
Yeah that's probably a good idea although it would be a bit silly to pass a null value key/value pair in the first place. It does make the logic slightly more robust.
