### ISSUE TITLE
withJson method is missing from Response class

### ISSUE THREAD

**Issue by hhovakimyan** [slimphp/Slim-Psr7#152]
I am trying to upgrade Slim framework used in my project from version 3 to version 4 and during the process I suddenly found out that `withJson` method has gone from the Response class. I want to understand why it is gone? I understand that Response class implements PSR-7 ResponseInterface, where withJson method is not included. But I don't think implementing ResponseInterface forbids Response class having some helper methods which will be very helpful.

**Comment by l0gicgate** [comment]
You need to use https://github.com/slimphp/Slim-Http decorators to have access to the old helper methods.
