### ISSUE TITLE
"Provides psr-17" in composer

### ISSUE THREAD

**Issue by webmaster777** [slimphp/Slim-Psr7#163]
The library provides all required PSR-17 interfaces. Shouldn't it be able to add `"psr/http-factory-implementation": "1.0"` to the `provide` key in `composer.json`?

Just like Guzzle and Diactoros do. See https://packagist.org/providers/psr/http-factory-implementation. 

I want to use a library that requires `psr/http-factory-implementation ^1.0` and I want to use this package.

**Comment by danopz** [comment]
Thought I added it back then in #17 but looks like I somehow forgot that one. Just go ahead and create a PR I would say :smiley:
