### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by andy-preston** [slimphp/Slim-Psr7#180]
Coming to this as a PSR-7 newbie either some documentation or a link in the readme to where the documentation can be found would be very very helpful.

**Comment by l0gicgate** [comment]
This library isn't being used as a standalone library for anything, I'm not sure what there is to document. 

The [PHP-FIG documentation](https://www.php-fig.org/psr/psr-7/) might be what you're looking for though and it is on our README.

**Comment by andy-preston** [comment]
> This library isn't being used as a standalone library for anything, I'm not sure what there is to document.

I'm currently working on a tech-test for a microservices job that I'm implementing along these lines 
https://www.youtube.com/watch?v=v1I57-_Rsv0 ... for this project using any framework (however lightweight) is out of the question but using libraries is OK. And this library looked like exactly what I needed, sadly without documentation this would be troublesome.

Disregarding this, even frameworks need to be debugged and I'd be very disappointed indeed to find that a chunk of the framework I was working on didn't have any documentation.
