### ISSUE TITLE
Invalid URI characters in password or username are not reencoded

### ISSUE THREAD

**Issue by lletourn** [slimphp/Slim-Psr7#181]
https://github.com/slimphp/Slim-Psr7/blob/5dbd98f5a0194db8aeee4da3441e56a1d816360b/src/Factory/UriFactory.php#L69
createFromGlobals takes the PHP_AUTH_USER,PHP_AUTH_PWD as-is without rencoding them.
This causes Uri::__tostring to ouput an invalid RFC3986 string

Uri->withUserInfo rencodes the given values and should be used instead of passing them directly to the constructor.

**Comment by lletourn** [comment]
If PHP_AUTH_PWD contains a ?, $, # (ie: 'abc?def')
This causes Uri->tostring() to generate URLs that can't be parsed by parse_url because they are not encoded.

Constructor has a different mecanism than using withUserInfo

**Comment by l0gicgate** [comment]
@lletourn good catch, you're more than welcome to raise a PR so we can fix it!

**Comment by lletourn** [comment]
Is the 3.X branch still maintained? The bug is there too so I'd need to have 2 PRs one for 4.x and one for 3.x

Thanks

**Comment by l0gicgate** [comment]
@lletourn the 3.x branch is in security mode only at the moment. It's a real pain to do releases but I might do an exception for this as I'm sure you're not the only one affected.
