### ISSUE TITLE
Psr7 update issue

### ISSUE THREAD

**Issue by AdroitAI** [slimphp/Slim-Psr7#183]
my php version is 8.0 and psr version is 7
but this shows me this error

 Problem 1
    - Root composer.json requires slim/psr7 ^0.5 -> satisfiable by slim/psr7[0.5.0].
    - slim/psr7 0.5.0 requires php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
  Problem 2
    - phpunit/phpunit[7.5.0, ..., 7.5.20] require php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit ^7.5 -> satisfiable by phpunit/phpunit[7.5.0, ..., 7.5.20].

**Comment by l0gicgate** [comment]
You need to manually update to version 1.3.0, composer will not bump to a major version for you. In your composer.json file change the dependency to:
```
"slim/psr7": "^1.3.0"
```

Remove your composer.lock file and run `composer update`
