### ISSUE TITLE
Issue with empty response with php builtin server

### ISSUE THREAD

**Issue by dominikzogg** [slimphp/Slim-Psr7#189]
Cause i wanted to debug why my framework gets slower in benchmark since i've added typed properties i tried to build a benchmark with the build in php server.

While doing so i run into the issue, that i can do only one successfully request and after that i get responses like that instead of an empty response as expected.

```
PĀĨ+|�
Host: default.development:8080
Date: Tue, 16 Mar 2021 20:50:21 GMT
Connection: close
X-Powered-By: PHP/7.4.16
Content-type: text/html; charset=utf-8
```

Cause i had (to be honest) still don't have an idea of the problem, i tried to compare with slim, to know if its a bug in my framework or in `slim/psr7` which i used with both framework.

Slim behaves the same (faulty) as my framework with `slim/psr7`, and both run fine with `laminas/laminas-diactoros`

Slim example:

```php
<?php

use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\Factory\AppFactory;

require __DIR__ . '/../vendor/autoload.php';

$app = AppFactory::create();

$app->get('/', function (Request $request, Response $response): Response {
    $response->getBody()->write("");
    return $response;
});

$app->run();
```

Run with the following command:

```
php -S 0.0.0.0:8080 -t /path/to/demo/public /path/to/demo/public/index.php
```

A dummy with standalone `slim/psr7` i didn't run into the issue:

```php
<?php

declare(strict_types=1);

namespace App;

use Slim\Psr7\Factory\ResponseFactory;

$loader = require __DIR__.'/../vendor/autoload.php';

$responseFactory = new ResponseFactory();

$response = $responseFactory->createResponse();
$response->getBody()->write('');

$statusCode = $response->getStatusCode();

header(sprintf(
    'HTTP/%s %s %s',
    $response->getProtocolVersion(),
    $statusCode,
    $response->getReasonPhrase()
), true, $statusCode);

foreach ($response->getHeaders() as $name => $values) {
    foreach ($values as $value) {
        header(sprintf('%s: %s', $name, $value), false);
    }
}

$body = $response->getBody();

if ($body->isSeekable()) {
    $body->rewind();
}

while (!$body->eof()) {
    echo $body->read(256);
}
```

About the system:

```
Ubuntu 20.04

PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies
    with blackfire v1.51.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire
```

**Comment by dominikzogg** [comment]
Dropping blackfire didn't help.

It's getting even uglier: it only happens in virtual enviroment (kvm, docker) in my tests...

Ev. its an ugly php core bug.

**Comment by dominikzogg** [comment]
@nikic while trying to get a minimal standalone demo for performance typed/not typed properties comparsion for my framework i run into this issue. Any clue what i could be?

**Comment by nikic** [comment]
I was able to reproduce this issue with the Ubuntu php package, but not my own PHP 7.4 build. It also went away after `sudo apt remote php-pcov`. Could you be using that extension as well?

**Comment by dominikzogg** [comment]
@nikic yes I do
