### ISSUE TITLE
Construction of a Uri object

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim-Psr7#2]
How should we construct a `Uri` object?  
Our current constructor is:

```php
public function __construct($scheme, $host, $port = null, $path = '/', $query = '', $fragment = '', $user = '', $password = '')
```
Should it be changed?

I think that the most common use-case is that the user has a string representation of a URI (e.g. "http://example.com/foo") & currently we use a factory called `createFromString` for this case.  

Should we update the way we create `Uri`s for Slim 4? These are the choices for construction of a `Uri`:

1. `$uri = new Uri('http', 'example.com', '/foo'):`  (as current)
2. `$uri = new Uri("http://example.com/foo"):`    (constructor takes a string)
3. `$uri = Uri::createFromString("http://example.com.foo"):`  (static factory in `Uri` class)

Note that we also want to support the upcoming [http-interop's factories](https://github.com/http-interop/http-factory) (PSR-17), so we'll also have this way to create a `Uri` from a string:  

`$uri = UriFactory::createUri("http://example.com/foo");`

Any preferences to how we should create `Uri`s in addition to `UriFactory::createUri()` ?

**Comment by tuupola** [comment]
I prefer `$uri = new Uri("http://example.com/foo");` approach.

**Comment by codeguy** [comment]
What @tuupola said

**Comment by akrabat** [comment]
Done.
