### ISSUE TITLE
Illegal offset type in isset or empty when getting attribute from request

### ISSUE THREAD

**Issue by robbelroot** [slimphp/Slim-Psr7#257]
Hey guys,

i'm getting this warning:
Warning: Illegal offset type in isset or empty (myproject..)\vendor\slim\psr7\src\Request.php on line 334.

when i'm trying to get an attribute from the request like this:
`$user = $request->getAttribute('user');`.

When looking into that file I can see this:
```
    /**
     * {@inheritdoc}
     */
    public function getAttribute($name, $default = null)
    {
        return isset($this->attributes[$name]) ? $this->attributes[$name] : $default;
    }
```

Maybe this version would be better, to avoid that warning?
```
    /**
     * {@inheritdoc}
     */
    public function getAttribute($name, $default = null)
    {
        return array_key_exists($name, $this->attributes) ? $this->attributes[$name] : $default;
    }
```
**EDIT:**
I actually made a mistake myself, providing a wrong index/key to the `getAttribute`-Function. With a string it's working.. Sorry

**Comment by l0gicgate** [comment]
Can I close this @robbelroot?

**Comment by robbelroot** [comment]
@l0gicgate 
> Can I close this @robbelroot?

Yeah, you can :)
