### ISSUE TITLE
New version with `psr/http-message` 2 support

### ISSUE THREAD

**Issue by Ayesh** [slimphp/Slim-Psr7#296]
PSR-7 v2 support was added in #289, but there is no version released.

Please cut a new release with the recent changes included. 

Thank you.

**Comment by clownmeister** [comment]
I would be most grateful as well. Looking for workaround at the moment.

**Comment by willy-opale** [comment]
I guess the only work around that comes to mind is forking the repo and implementing the commit ourselves. It seems Slim is dying slowly, as opposed to Symfony and other frameworks.

**Comment by trendschau** [comment]
Yes, that would be really great, I start to get errors with other libraries and switched to dev-master in composer now, but it would be great if you can add a release.

**Comment by piotr-cz** [comment]
At this moment there is one PR pending for the 1.7.0 milestone: https://github.com/slimphp/Slim-Psr7/milestone/14.
I think if we want new release, we have to move https://github.com/slimphp/Slim-Psr7/pull/294 forward
