### ISSUE TITLE
ParsedBody

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim-Psr7#4]
I'm removing non-PSR-7 methods from Slim-Psr7 

However, when it comes to the parsed body of the Request object, Should Slim-Psr7 continue to handle it's own decoding of body using the media types or should this functionality be moved elsewhere?

**Comment by geggleto** [comment]
The functionality should not change. 
However we should be making it easy to add in our own decoders.

How we do that... I have no idea, but probably in some sort of Middleware.

**Comment by mathmarques** [comment]
Shouldn't we move this to Middleware?
On ExpressJS we use middlewares([see the middleware here](https://github.com/expressjs/body-parser)) and works well. 

Another thing with ParsedBody:
Setting `$bodyParsed` to false was a [fix for an issue](https://github.com/slimphp/Slim/pull/1734). Maybe if we change the way `parsedBody()` works, we could remove this.
