### ISSUE TITLE
Use of type hints and return types

### ISSUE THREAD

**Issue by holtkamp** [slimphp/Slim-Psr7#58]
Since PHP `7.1` is used, nullable and `void` return types could be adopted. 

I was wondering: what is the level of ambition regarding this possibility for some more strictness by adopting type hints and return types?

For an overview see: 
- https://mlocati.github.io/articles/php-type-hinting.html
- https://www.php.net/manual/en/migration71.new-features.php

**Comment by l0gicgate** [comment]
I’m all for type hinting and return types to be as strict as possible. The problem is that most of the implementations have to match the function signatures from the PSR-7 interfaces which are not type hinted.

**Comment by holtkamp** [comment]
>The problem is that most of the implementations have to match the function signatures from the PSR-7 interfaces which are not type hinted.

Ah, of course 🤦‍♂ 

But for the "return types" I believe it should be able to increase strictness...

**Comment by holtkamp** [comment]
To get an impression, an experimental commit: https://github.com/holtkamp/Slim-Psr7/commit/3934b95592c7ed39b6213f1f64da0eac111ee922

PHPUnit fails, but this seems not related to the types / also fails on a clean clone.
