### ISSUE TITLE
PHPUnit error

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim-Psr7#65]
I just cloned the repository, run `composer install` and then tried `phpunit`. I got the following error and was wondering, if that is only in my environment?
```
1) Slim\Tests\Psr7\Integration\ServerRequestTest::testGetUploadedFiles
RuntimeException: Could not create Stream. Check your config

...\vendor\php-http\psr7-integration-tests\src\BaseTest.php:111
...\vendor\php-http\psr7-integration-tests\src\ServerRequestIntegrationTest.php:83
```

**Comment by l0gicgate** [comment]
Sounds like a permission issue on the cloned repository? All tests pass in CI.
