### ISSUE TITLE
PHPUnit problems with getallheaders()

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim-Psr7#72]
In #70 the file `tests/Assets/PhpGetAllHeaders.php` had been removed. This breaks PHPUnit on my system (Win10, PHP 7.1), because the following condition
https://github.com/slimphp/Slim-Psr7/blob/3f9b6ae466bae72a846e5ba7f85a2519497a83d0/src/Headers.php#L266
always returns false (even if the function is defined in the `Slim\Psr7` namespace via the file `tests/Assets/PhpFunctionOverrides.php`).

### Test Output
```
There were 4 failures:

1) Slim\Tests\Psr7\Factory\ServerRequestFactoryTest::testCreateFromGlobals
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'application/json'
+''

D:\GitHub\Slim-Psr7\tests\Factory\ServerRequestFactoryTest.php:82

2) Slim\Tests\Psr7\Factory\ServerRequestFactoryTest::testCreateFromGlobalsWithParsedBody
null does not match expected type "array".

D:\GitHub\Slim-Psr7\tests\Factory\ServerRequestFactoryTest.php:110

3) Slim\Tests\Psr7\Factory\ServerRequestFactoryTest::testCreateFromGlobalsParsesBodyWithFragmentedContentType
null does not match expected type "array".

D:\GitHub\Slim-Psr7\tests\Factory\ServerRequestFactoryTest.php:172

4) Slim\Tests\Psr7\HeadersTest::testCreateFromGlobals
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'accept' => Array (...)
 )

D:\GitHub\Slim-Psr7\tests\HeadersTest.php:27
```
It seems that only failures 1 and 4 are directly connected, as the other failures remain even if I add the function `getallheaders()` to the root namespace.

**Comment by adriansuter** [comment]
It appears as if the method `function_exists()` is searching in the root namespace only, if there is no namespace prefix at all.

I made the following test:
```php
<?php

namespace ns;

function test() {
	return '1';
}

if ( function_exists('test') ) {
	echo test();
} else {
	echo '0';
}

if ( function_exists('ns\test') ) {
	echo test();
} else {
	echo '0';
}
```
The result was `01`. So the first condition was `false`, the seond `true`. Is this as expected? If so, then we need to make sure that in case php does not define `getallheaders`, we define it in the root namespace.

**Comment by l0gicgate** [comment]
So we should probably append a backslash to the function name like so:

**In Headers::createFromGlobals()**
```php
    public static function createFromGlobals()
    {
        $headers = null;

        if (function_exists('\getallheaders')) {
            $headers = \getallheaders();
        }

        if (!is_array($headers)) {
            $headers = [];
        }

        return new static($headers);
    }
```

**Comment by adriansuter** [comment]
But then we cannot override this method for unit testing.

**Comment by l0gicgate** [comment]
I think we can just do `function_exists('\getallheaders')` and then use `$headers = getallheaders()`

**Comment by adriansuter** [comment]
If we check for `function_exists('\getallheaders')`, then the phpunit tests would not run correctly on systems without `getallheaders()`, because the condition would be false on these systems (but the test case expects this condition to be true).

**Comment by l0gicgate** [comment]
could do `function_exists('\getallheaders') || function_exists('Slim\getallheaders')`

**Comment by adriansuter** [comment]
Then we insert a condition into the library source code that is actually only used by unit testing. I think there is no other way: we need a polyfill to make sure that the function exists on the root namespace. Either we write our own, or define one in composer require-dev.

**Comment by l0gicgate** [comment]
We can use `https://github.com/ralouphie/getallheaders`

**Comment by adriansuter** [comment]
That's a good idea.
