### ISSUE TITLE
Missing docblocks

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim-Psr7#92]
The class `Cookies` does not extend nor implement anything. But there are some docblocks like the following

https://github.com/slimphp/Slim-Psr7/blob/9cdb71a3577e8ab5546c6135a326e8e6fb7bea83/src/Cookies.php#L68-L71

Where do they inherit from?

**Comment by l0gicgate** [comment]
They originally did from the interface. That needs to be fixed!
